package com.ssm.farming.mapper;

import com.ssm.farming.pojo.Expert;
import com.ssm.farming.pojo.ExpertExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ExpertMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int countByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int deleteByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int insert(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int insertSelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    List<Expert> selectByExample(ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    Expert selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Expert record, @Param("example") ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Expert record, @Param("example") ExpertExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Expert record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_expert
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Expert record);
}