package com.ssm.farming.mapper;

import com.ssm.farming.pojo.Farmer;
import com.ssm.farming.pojo.FarmerExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface FarmerMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int countByExample(FarmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int deleteByExample(FarmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int insert(Farmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int insertSelective(Farmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    List<Farmer> selectByExample(FarmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    Farmer selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Farmer record, @Param("example") FarmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Farmer record, @Param("example") FarmerExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Farmer record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Farmer record);
}