package com.ssm.farming.mapper;

import com.ssm.farming.pojo.Reporter;
import com.ssm.farming.pojo.ReporterExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ReporterMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int countByExample(ReporterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int deleteByExample(ReporterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int insert(Reporter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int insertSelective(Reporter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    List<Reporter> selectByExample(ReporterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    Reporter selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Reporter record, @Param("example") ReporterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Reporter record, @Param("example") ReporterExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Reporter record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_reporter
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Reporter record);
}