package com.ssm.farming.pojo;

public class Expert {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.aspect_1
     *
     * @mbggenerated
     */
    private String aspect1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.aspect_2
     *
     * @mbggenerated
     */
    private String aspect2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.aspect_3
     *
     * @mbggenerated
     */
    private String aspect3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_expert.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.id
     *
     * @return the value of tb_expert.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.id
     *
     * @param id the value for tb_expert.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.address
     *
     * @return the value of tb_expert.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.address
     *
     * @param address the value for tb_expert.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.aspect_1
     *
     * @return the value of tb_expert.aspect_1
     *
     * @mbggenerated
     */
    public String getAspect1() {
        return aspect1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.aspect_1
     *
     * @param aspect1 the value for tb_expert.aspect_1
     *
     * @mbggenerated
     */
    public void setAspect1(String aspect1) {
        this.aspect1 = aspect1 == null ? null : aspect1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.aspect_2
     *
     * @return the value of tb_expert.aspect_2
     *
     * @mbggenerated
     */
    public String getAspect2() {
        return aspect2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.aspect_2
     *
     * @param aspect2 the value for tb_expert.aspect_2
     *
     * @mbggenerated
     */
    public void setAspect2(String aspect2) {
        this.aspect2 = aspect2 == null ? null : aspect2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.aspect_3
     *
     * @return the value of tb_expert.aspect_3
     *
     * @mbggenerated
     */
    public String getAspect3() {
        return aspect3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.aspect_3
     *
     * @param aspect3 the value for tb_expert.aspect_3
     *
     * @mbggenerated
     */
    public void setAspect3(String aspect3) {
        this.aspect3 = aspect3 == null ? null : aspect3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_expert.user_id
     *
     * @return the value of tb_expert.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_expert.user_id
     *
     * @param userId the value for tb_expert.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}