package com.ssm.farming.pojo;

import java.util.ArrayList;
import java.util.List;

public class FarmerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public FarmerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNull() {
            addCriterion("user_id is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("user_id is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("user_id =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("user_id <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("user_id >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("user_id >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("user_id <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("user_id <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("user_id in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("user_id not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("user_id between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("user_id not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andSpecies1IsNull() {
            addCriterion("species_1 is null");
            return (Criteria) this;
        }

        public Criteria andSpecies1IsNotNull() {
            addCriterion("species_1 is not null");
            return (Criteria) this;
        }

        public Criteria andSpecies1EqualTo(String value) {
            addCriterion("species_1 =", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1NotEqualTo(String value) {
            addCriterion("species_1 <>", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1GreaterThan(String value) {
            addCriterion("species_1 >", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1GreaterThanOrEqualTo(String value) {
            addCriterion("species_1 >=", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1LessThan(String value) {
            addCriterion("species_1 <", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1LessThanOrEqualTo(String value) {
            addCriterion("species_1 <=", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1Like(String value) {
            addCriterion("species_1 like", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1NotLike(String value) {
            addCriterion("species_1 not like", value, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1In(List<String> values) {
            addCriterion("species_1 in", values, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1NotIn(List<String> values) {
            addCriterion("species_1 not in", values, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1Between(String value1, String value2) {
            addCriterion("species_1 between", value1, value2, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies1NotBetween(String value1, String value2) {
            addCriterion("species_1 not between", value1, value2, "species1");
            return (Criteria) this;
        }

        public Criteria andSpecies2IsNull() {
            addCriterion("species_2 is null");
            return (Criteria) this;
        }

        public Criteria andSpecies2IsNotNull() {
            addCriterion("species_2 is not null");
            return (Criteria) this;
        }

        public Criteria andSpecies2EqualTo(String value) {
            addCriterion("species_2 =", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2NotEqualTo(String value) {
            addCriterion("species_2 <>", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2GreaterThan(String value) {
            addCriterion("species_2 >", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2GreaterThanOrEqualTo(String value) {
            addCriterion("species_2 >=", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2LessThan(String value) {
            addCriterion("species_2 <", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2LessThanOrEqualTo(String value) {
            addCriterion("species_2 <=", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2Like(String value) {
            addCriterion("species_2 like", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2NotLike(String value) {
            addCriterion("species_2 not like", value, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2In(List<String> values) {
            addCriterion("species_2 in", values, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2NotIn(List<String> values) {
            addCriterion("species_2 not in", values, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2Between(String value1, String value2) {
            addCriterion("species_2 between", value1, value2, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies2NotBetween(String value1, String value2) {
            addCriterion("species_2 not between", value1, value2, "species2");
            return (Criteria) this;
        }

        public Criteria andSpecies3IsNull() {
            addCriterion("species_3 is null");
            return (Criteria) this;
        }

        public Criteria andSpecies3IsNotNull() {
            addCriterion("species_3 is not null");
            return (Criteria) this;
        }

        public Criteria andSpecies3EqualTo(String value) {
            addCriterion("species_3 =", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3NotEqualTo(String value) {
            addCriterion("species_3 <>", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3GreaterThan(String value) {
            addCriterion("species_3 >", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3GreaterThanOrEqualTo(String value) {
            addCriterion("species_3 >=", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3LessThan(String value) {
            addCriterion("species_3 <", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3LessThanOrEqualTo(String value) {
            addCriterion("species_3 <=", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3Like(String value) {
            addCriterion("species_3 like", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3NotLike(String value) {
            addCriterion("species_3 not like", value, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3In(List<String> values) {
            addCriterion("species_3 in", values, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3NotIn(List<String> values) {
            addCriterion("species_3 not in", values, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3Between(String value1, String value2) {
            addCriterion("species_3 between", value1, value2, "species3");
            return (Criteria) this;
        }

        public Criteria andSpecies3NotBetween(String value1, String value2) {
            addCriterion("species_3 not between", value1, value2, "species3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_farmer
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table tb_farmer
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}