package com.ssm.farming.pojo;

public class Farmer {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.species_1
     *
     * @mbggenerated
     */
    private String species1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.species_2
     *
     * @mbggenerated
     */
    private String species2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_farmer.species_3
     *
     * @mbggenerated
     */
    private String species3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.id
     *
     * @return the value of tb_farmer.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.id
     *
     * @param id the value for tb_farmer.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.address
     *
     * @return the value of tb_farmer.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.address
     *
     * @param address the value for tb_farmer.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.user_id
     *
     * @return the value of tb_farmer.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.user_id
     *
     * @param userId the value for tb_farmer.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.species_1
     *
     * @return the value of tb_farmer.species_1
     *
     * @mbggenerated
     */
    public String getSpecies1() {
        return species1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.species_1
     *
     * @param species1 the value for tb_farmer.species_1
     *
     * @mbggenerated
     */
    public void setSpecies1(String species1) {
        this.species1 = species1 == null ? null : species1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.species_2
     *
     * @return the value of tb_farmer.species_2
     *
     * @mbggenerated
     */
    public String getSpecies2() {
        return species2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.species_2
     *
     * @param species2 the value for tb_farmer.species_2
     *
     * @mbggenerated
     */
    public void setSpecies2(String species2) {
        this.species2 = species2 == null ? null : species2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_farmer.species_3
     *
     * @return the value of tb_farmer.species_3
     *
     * @mbggenerated
     */
    public String getSpecies3() {
        return species3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_farmer.species_3
     *
     * @param species3 the value for tb_farmer.species_3
     *
     * @mbggenerated
     */
    public void setSpecies3(String species3) {
        this.species3 = species3 == null ? null : species3.trim();
    }
}