package com.ssm.farming.pojo;

import java.math.BigDecimal;

public class Product {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.price
     *
     * @mbggenerated
     */
    private BigDecimal price;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.stock
     *
     * @mbggenerated
     */
    private String stock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.status
     *
     * @mbggenerated
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.classification
     *
     * @mbggenerated
     */
    private String classification;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.place
     *
     * @mbggenerated
     */
    private Integer place;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.description
     *
     * @mbggenerated
     */
    private String description;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_product.image
     *
     * @mbggenerated
     */
    private String image;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.id
     *
     * @return the value of tb_product.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.id
     *
     * @param id the value for tb_product.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.name
     *
     * @return the value of tb_product.name
     *
     * @mbggenerated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.name
     *
     * @param name the value for tb_product.name
     *
     * @mbggenerated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.price
     *
     * @return the value of tb_product.price
     *
     * @mbggenerated
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.price
     *
     * @param price the value for tb_product.price
     *
     * @mbggenerated
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.stock
     *
     * @return the value of tb_product.stock
     *
     * @mbggenerated
     */
    public String getStock() {
        return stock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.stock
     *
     * @param stock the value for tb_product.stock
     *
     * @mbggenerated
     */
    public void setStock(String stock) {
        this.stock = stock == null ? null : stock.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.status
     *
     * @return the value of tb_product.status
     *
     * @mbggenerated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.status
     *
     * @param status the value for tb_product.status
     *
     * @mbggenerated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.classification
     *
     * @return the value of tb_product.classification
     *
     * @mbggenerated
     */
    public String getClassification() {
        return classification;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.classification
     *
     * @param classification the value for tb_product.classification
     *
     * @mbggenerated
     */
    public void setClassification(String classification) {
        this.classification = classification == null ? null : classification.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.place
     *
     * @return the value of tb_product.place
     *
     * @mbggenerated
     */
    public Integer getPlace() {
        return place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.place
     *
     * @param place the value for tb_product.place
     *
     * @mbggenerated
     */
    public void setPlace(Integer place) {
        this.place = place;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.description
     *
     * @return the value of tb_product.description
     *
     * @mbggenerated
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.description
     *
     * @param description the value for tb_product.description
     *
     * @mbggenerated
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_product.image
     *
     * @return the value of tb_product.image
     *
     * @mbggenerated
     */
    public String getImage() {
        return image;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_product.image
     *
     * @param image the value for tb_product.image
     *
     * @mbggenerated
     */
    public void setImage(String image) {
        this.image = image == null ? null : image.trim();
    }
}