package com.ssm.farming.pojo;

public class Reporter {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reporter.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reporter.office
     *
     * @mbggenerated
     */
    private String office;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_reporter.user_id
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reporter.id
     *
     * @return the value of tb_reporter.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reporter.id
     *
     * @param id the value for tb_reporter.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reporter.office
     *
     * @return the value of tb_reporter.office
     *
     * @mbggenerated
     */
    public String getOffice() {
        return office;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reporter.office
     *
     * @param office the value for tb_reporter.office
     *
     * @mbggenerated
     */
    public void setOffice(String office) {
        this.office = office == null ? null : office.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_reporter.user_id
     *
     * @return the value of tb_reporter.user_id
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_reporter.user_id
     *
     * @param userId the value for tb_reporter.user_id
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}